# Site settings
title: Isaac Ngui
description: A personal webpage for Isaac Ngui
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://imngui.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Isaac Ngui
user_description: I am a Ph.D. student at the University of Illinois at Urbana-Champaign who joined Dr. Nancy Amato's lab in Fall 2020. I graduated from the University of Wisconsin Milwaukee where I majored in computer science and minored in math.
user_title: Computer Science Ph.D. Stduent
email: ingui2@illinois.edu
# twitter_username: lorem_ipsum
github_username:  imngui
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
